[versions]
agp = "8.7.0"
work = "2.9.1"
lifecycle = "2.8.6"
material = "1.12.0"
libsu = "6.0.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }

[libraries]
androidx-appcompat-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-constraintlayout-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-databinding-viewbinding = { group = "androidx.databinding", name = "viewbinding", version = "8.7.0" }
androidx-preference-preference = { group = "androidx.preference", name = "preference", version = "1.2.1" }
androidx-palette-palette = { group = "androidx.palette", name = "palette", version = "1.0.0" }

androidx-work-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

com-github-topjohnwu-libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
com-github-topjohnwu-libsu-service = { group = "com.github.topjohnwu.libsu", name = "service", version.ref = "libsu" }
com-github-topjohnwu-libsu-nio = { group = "com.github.topjohnwu.libsu", name = "nio", version.ref = "libsu" }

com-intuit-sdp-sdp-android = { group = "com.intuit.sdp", name = "sdp-android", version = "1.1.1" }

material = { module = "com.google.android.material:material", version.ref = "material" }